{% set name = "doubtlab" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f745b6d9866c767af9773c3a08efafb6d0e13cbe58a3e3e8bed094a480127065

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  {% set pyver = ">=3.7,<4.0" %}
  host:
    - pip
    - python {{ pyver }}
  run:
    - python {{ pyver }}
    - cleanlab >=1.0
    - pandas >=1.3.3    
    - scikit-learn >=1.0.0

test:
  imports:
    - {{ name|lower }}
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://koaning.github.io/doubtlab/
  summary: Don't Blindly Trust Your Labels
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    This repository contains general tricks that may help you find bad, 
    or noisy, labels in your dataset. The hope is that this repository 
    makes it easier for folks to quickly check their own datasets before 
    they invest too much time and compute on gridsearch.
  doc_url: https://koaning.github.io/doubtlab/
  dev_url: https://github.com/koaning/doubtlab

extra:
  recipe-maintainers:
    - sugatoray
    - koaning
